name: Compilation du projet Maven
on:
    push:
        branches:
            - main
    workflow_dispatch:
#Ma definition de job qui va sexecuter sur la branche...     
jobs:
    compilation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - name: Set up JDK 25
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '25'
            - name: Fournir access au runner
              run: chmod +x mvnw
            - name: Compilation du projet Maven
              run: ./mvnw compile

#Ecrire les 17 tests qui echouent actuellement 
# Ajouter une etape qui execute les tests que si la compilation reussi
            - name: Build and run tests
              run: ./mvnw -B clean verify